<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\DataSource\Comment\CommentRow;

/**
 * @method ?CommentRow fetchRow()
 * @method CommentRow[] fetchRows()
 */
abstract class CommentTableSelect_ extends TableSelect
{
}
