<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Comment\CommentRecord;
use Atlas\Mapper\DataSource\Comment\CommentRecordSet;

/**
 * @method ?CommentRecord fetchRecord()
 * @method CommentRecord[] fetchRecords()
 * @method CommentRecordSet fetchRecordSet()
 * @method ?CommentRow fetchRow()
 * @method CommentRow[] fetchRows()
 */
abstract class CommentSelect_ extends MapperSelect
{
}
