<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Comment\CommentRecord;
use Atlas\Mapper\DataSource\Comment\CommentRecordSet;
use Atlas\Mapper\DataSource\Comment\CommentSelect;
use Atlas\Mapper\DataSource\Comment\CommentTable;

/**
 * @method CommentTable getTable()
 * @method ?CommentRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?CommentRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method CommentRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method CommentRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method CommentRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method CommentRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method CommentSelect select(array $whereEquals = [])
 * @method CommentRecord newRecord(array $fields = [])
 * @method CommentRecord[] newRecords(array $fieldSets)
 * @method CommentRecordSet newRecordSet(array $records = [])
 * @method CommentRecord turnRowIntoRecord(CommentRow $row, array $loadRelated = [])
 * @method CommentRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Comment_ extends Mapper
{
}
