<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $comment_id INTEGER
 * @property mixed $related_type VARCHAR(255)
 * @property mixed $related_id INTEGER
 * @property mixed $body TEXT
 */
abstract class CommentRow_ extends Row
{
    protected mixed $comment_id = null;
    protected mixed $related_type = null;
    protected mixed $related_id = null;
    protected mixed $body = null;
}
