<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $comment_id INTEGER
 * @property mixed $related_type VARCHAR(255)
 * @property mixed $related_id INTEGER
 * @property mixed $body TEXT
 * @property \mixed $commentable
 * @method \Atlas\Mapper\DataSource\Comment\CommentRow getRow()
 */
abstract class CommentRecord_ extends Record
{
}
