/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Mapper\MapperSelect;
use <?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}Record" ?>;
use <?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}RecordSet" ?>;

/**
 * @method ?<?= $TYPE ?>Record fetchRecord()
 * @method <?= $TYPE ?>Record[] fetchRecords()
 * @method <?= $TYPE ?>RecordSet fetchRecordSet()
 * @method ?<?= $TYPE ?>Row fetchRow()
 * @method <?= $TYPE ?>Row[] fetchRows()
 */
abstract class <?= $TYPE ?>Select_ extends MapperSelect
{
}
