/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Mapper\RecordSet;
use <?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}Record" ?>;
use <?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}RecordSet" ?>;

/**
 * @method __construct(<?= $TYPE ?>Record[], callable $newRecordFactory)
 * @method <?= $TYPE ?>Record offsetGet($offset)
 * @method <?= $TYPE ?>Record appendNew(array $fields = [])
 * @method ?<?= $TYPE ?>Record getOneBy(array $whereEquals)
 * @method <?= $TYPE ?>RecordSet getAllBy(array $whereEquals)
 * @method ?<?= $TYPE ?>Record detachOneBy(array $whereEquals)
 * @method <?= $TYPE ?>RecordSet detachAllBy(array $whereEquals)
 * @method <?= $TYPE ?>RecordSet detachAll()
 * @method <?= $TYPE ?>RecordSet detachDeleted()
 */
abstract class <?= $TYPE ?>RecordSet_ extends RecordSet
{
}
