/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Mapper\MapperEvents;

abstract class <?= $TYPE ?>Events_ extends MapperEvents
{
}
