/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Table\Row;

/**
<?php foreach ($COLUMNS as $name => $info) {
    echo " * @property mixed \${$name} {$COLDEFS[$name]}" . PHP_EOL;
} ?>
 */
abstract class <?= $TYPE ?>Row_ extends Row
{
<?php foreach ($COLUMNS as $name => $info) {
    $default = ($info['default'] === null)
        ? 'null'
        : var_export($info['default'], true);

    echo "    protected mixed \${$name} = $default;" . PHP_EOL;
} ?>
}
