/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Table\TableSelect;
use <?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}Row" ?>;

/**
 * @method ?<?= $TYPE ?>Row fetchRow()
 * @method <?= $TYPE ?>Row[] fetchRows()
 */
abstract class <?= $TYPE ?>TableSelect_ extends TableSelect
{
}
