/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Mapper\Record;

/**
<?php foreach ($COLUMNS as $name => $info) {
    echo " * @property mixed \${$name} {$COLDEFS[$name]}" . PHP_EOL;
} ?>
<?php foreach ($RELATED as $name => $hint) {
    echo " * @property {$hint} \${$name}" . PHP_EOL;
} ?>
 * @method \<?= "{$NAMESPACE}\\{$TYPE}\\{$TYPE}" ?>Row getRow()
 */
abstract class <?= $TYPE ?>Record_ extends Record
{
}
