/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace <?= "{$NAMESPACE}\\{$TYPE}\\_generated" ?>;

use Atlas\Table\TableEvents;

abstract class <?= $TYPE ?>TableEvents_ extends TableEvents
{
}
