<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace {NAMESPACE};

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class {TYPE}Table extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return {TABLE};
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return {COLS};
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return {INFO};
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return {PRIMARY};
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return {AUTOINC};
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return {DEFAULT};
    }
}
