<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Author\AuthorRecord;
use Atlas\Mapper\DataSource\Author\AuthorRecordSet;

/**
 * @method ?AuthorRecord fetchRecord()
 * @method AuthorRecord[] fetchRecords()
 * @method AuthorRecordSet fetchRecordSet()
 * @method ?AuthorRow fetchRow()
 * @method AuthorRow[] fetchRows()
 */
abstract class AuthorSelect_ extends MapperSelect
{
}
