<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\DataSource\Author\AuthorRow;
use Atlas\Mapper\DataSource\Author\AuthorTableSelect;

/**
 * @method ?AuthorRow fetchRow(mixed $primaryVal)
 * @method AuthorRow[] fetchRows(array $primaryVals)
 * @method AuthorTableSelect select(array $whereEquals = [])
 * @method AuthorRow newRow(array $cols = [])
 * @method AuthorRow newSelectedRow(array $cols)
 */
abstract class AuthorTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'authors';

    public const COLUMNS = [
        'author_id' => [
            'name' => 'author_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'author_id',    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = 'author_id';

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = AuthorRow;
}
