<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author\_generated;

use Atlas\Mapper\Related;

abstract class AuthorRelated_ extends Related
{
}
