<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $author_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 */
abstract class AuthorRow_ extends Row
{
    protected mixed $author_id = null;
    protected mixed $name = null;
}
