<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Author\AuthorRecord;
use Atlas\Mapper\DataSource\Author\AuthorRecordSet;
use Atlas\Mapper\DataSource\Author\AuthorSelect;
use Atlas\Mapper\DataSource\Author\AuthorTable;

/**
 * @method AuthorTable getTable()
 * @method ?AuthorRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?AuthorRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method AuthorRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method AuthorRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method AuthorRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method AuthorRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method AuthorSelect select(array $whereEquals = [])
 * @method AuthorRecord newRecord(array $fields = [])
 * @method AuthorRecord[] newRecords(array $fieldSets)
 * @method AuthorRecordSet newRecordSet(array $records = [])
 * @method AuthorRecord turnRowIntoRecord(AuthorRow $row, array $loadRelated = [])
 * @method AuthorRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Author_ extends Mapper
{
}
