<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecord;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecordSet;
use Atlas\Mapper\DataSource\Bidifoo\BidifooSelect;
use Atlas\Mapper\DataSource\Bidifoo\BidifooTable;

/**
 * @method BidifooTable getTable()
 * @method ?BidifooRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?BidifooRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method BidifooRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method BidifooRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method BidifooRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method BidifooRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method BidifooSelect select(array $whereEquals = [])
 * @method BidifooRecord newRecord(array $fields = [])
 * @method BidifooRecord[] newRecords(array $fieldSets)
 * @method BidifooRecordSet newRecordSet(array $records = [])
 * @method BidifooRecord turnRowIntoRecord(BidifooRow $row, array $loadRelated = [])
 * @method BidifooRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Bidifoo_ extends Mapper
{
}
