<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRow;

/**
 * @method ?BidifooRow fetchRow()
 * @method BidifooRow[] fetchRows()
 */
abstract class BidifooTableSelect_ extends TableSelect
{
}
