<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecord;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecordSet;

/**
 * @method ?BidifooRecord fetchRecord()
 * @method BidifooRecord[] fetchRecords()
 * @method BidifooRecordSet fetchRecordSet()
 * @method ?BidifooRow fetchRow()
 * @method BidifooRow[] fetchRows()
 */
abstract class BidifooSelect_ extends MapperSelect
{
}
