<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $bidifoo_id INTEGER
 * @property mixed $bidibar_id INTEGER
 * @property mixed $name VARCHAR(10)
 */
abstract class BidifooRow_ extends Row
{
    protected mixed $bidifoo_id = null;
    protected mixed $bidibar_id = null;
    protected mixed $name = null;
}
