<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecord;
use Atlas\Mapper\DataSource\Bidifoo\BidifooRecordSet;

/**
 * @method __construct(BidifooRecord[], callable $newRecordFactory)
 * @method BidifooRecord offsetGet($offset)
 * @method BidifooRecord appendNew(array $fields = [])
 * @method ?BidifooRecord getOneBy(array $whereEquals)
 * @method BidifooRecordSet getAllBy(array $whereEquals)
 * @method ?BidifooRecord detachOneBy(array $whereEquals)
 * @method BidifooRecordSet detachAllBy(array $whereEquals)
 * @method BidifooRecordSet detachAll()
 * @method BidifooRecordSet detachDeleted()
 */
abstract class BidifooRecordSet_ extends RecordSet
{
}
