<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $bidifoo_id INTEGER
 * @property mixed $bidibar_id INTEGER
 * @property mixed $name VARCHAR(10)
 * @property ?\Atlas\Mapper\DataSource\Bidibar\BidibarRecord $bidibar
 * @method \Atlas\Mapper\DataSource\Bidifoo\BidifooRow getRow()
 */
abstract class BidifooRecord_ extends Record
{
}
