<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidifoo\_generated;

use Atlas\Mapper\Related;

abstract class BidifooRelated_ extends Related
{
}
