<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Summary\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Summary\SummaryRecord;
use Atlas\Mapper\DataSource\Summary\SummaryRecordSet;
use Atlas\Mapper\DataSource\Summary\SummarySelect;
use Atlas\Mapper\DataSource\Summary\SummaryTable;

/**
 * @method SummaryTable getTable()
 * @method ?SummaryRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?SummaryRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method SummaryRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method SummaryRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method SummaryRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method SummaryRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method SummarySelect select(array $whereEquals = [])
 * @method SummaryRecord newRecord(array $fields = [])
 * @method SummaryRecord[] newRecords(array $fieldSets)
 * @method SummaryRecordSet newRecordSet(array $records = [])
 * @method SummaryRecord turnRowIntoRecord(SummaryRow $row, array $loadRelated = [])
 * @method SummaryRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Summary_ extends Mapper
{
}
