<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Summary\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Summary\SummaryRecord;
use Atlas\Mapper\DataSource\Summary\SummaryRecordSet;

/**
 * @method ?SummaryRecord fetchRecord()
 * @method SummaryRecord[] fetchRecords()
 * @method SummaryRecordSet fetchRecordSet()
 * @method ?SummaryRow fetchRow()
 * @method SummaryRow[] fetchRows()
 */
abstract class SummarySelect_ extends MapperSelect
{
}
