<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Summary\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $summary_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $reply_count INTEGER NOT NULL
 * @property mixed $view_count INTEGER NOT NULL
 * @property ?\Atlas\Mapper\DataSource\Thread\ThreadRecord $thread
 * @method \Atlas\Mapper\DataSource\Summary\SummaryRow getRow()
 */
abstract class SummaryRecord_ extends Record
{
}
