<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Nopkey\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Nopkey\NopkeyRecord;
use Atlas\Mapper\DataSource\Nopkey\NopkeyRecordSet;

/**
 * @method ?NopkeyRecord fetchRecord()
 * @method NopkeyRecord[] fetchRecords()
 * @method NopkeyRecordSet fetchRecordSet()
 * @method ?NopkeyRow fetchRow()
 * @method NopkeyRow[] fetchRows()
 */
abstract class NopkeySelect_ extends MapperSelect
{
}
