<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Employee\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Employee\EmployeeRecord;
use Atlas\Mapper\DataSource\Employee\EmployeeRecordSet;
use Atlas\Mapper\DataSource\Employee\EmployeeSelect;
use Atlas\Mapper\DataSource\Employee\EmployeeTable;

/**
 * @method EmployeeTable getTable()
 * @method ?EmployeeRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?EmployeeRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method EmployeeRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method EmployeeRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method EmployeeRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method EmployeeRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method EmployeeSelect select(array $whereEquals = [])
 * @method EmployeeRecord newRecord(array $fields = [])
 * @method EmployeeRecord[] newRecords(array $fieldSets)
 * @method EmployeeRecordSet newRecordSet(array $records = [])
 * @method EmployeeRecord turnRowIntoRecord(EmployeeRow $row, array $loadRelated = [])
 * @method EmployeeRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Employee_ extends Mapper
{
}
