<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Employee\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Employee\EmployeeRecord;
use Atlas\Mapper\DataSource\Employee\EmployeeRecordSet;

/**
 * @method ?EmployeeRecord fetchRecord()
 * @method EmployeeRecord[] fetchRecords()
 * @method EmployeeRecordSet fetchRecordSet()
 * @method ?EmployeeRow fetchRow()
 * @method EmployeeRow[] fetchRows()
 */
abstract class EmployeeSelect_ extends MapperSelect
{
}
