<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Employee\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property mixed $building INTEGER
 * @property mixed $floor INTEGER
 * @property \mixed $id
 * @method \Atlas\Mapper\DataSource\Employee\EmployeeRow getRow()
 */
abstract class EmployeeRecord_ extends Record
{
}
