<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tag\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Tag\TagRecord;
use Atlas\Mapper\DataSource\Tag\TagRecordSet;
use Atlas\Mapper\DataSource\Tag\TagSelect;
use Atlas\Mapper\DataSource\Tag\TagTable;

/**
 * @method TagTable getTable()
 * @method ?TagRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?TagRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method TagRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method TagRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method TagRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method TagRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method TagSelect select(array $whereEquals = [])
 * @method TagRecord newRecord(array $fields = [])
 * @method TagRecord[] newRecords(array $fieldSets)
 * @method TagRecordSet newRecordSet(array $records = [])
 * @method TagRecord turnRowIntoRecord(TagRow $row, array $loadRelated = [])
 * @method TagRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Tag_ extends Mapper
{
}
