<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tag\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Tag\TagRecord;
use Atlas\Mapper\DataSource\Tag\TagRecordSet;

/**
 * @method ?TagRecord fetchRecord()
 * @method TagRecord[] fetchRecords()
 * @method TagRecordSet fetchRecordSet()
 * @method ?TagRow fetchRow()
 * @method TagRow[] fetchRows()
 */
abstract class TagSelect_ extends MapperSelect
{
}
