<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tag\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\DataSource\Tag\TagRow;
use Atlas\Mapper\DataSource\Tag\TagTableSelect;

/**
 * @method ?TagRow fetchRow(mixed $primaryVal)
 * @method TagRow[] fetchRows(array $primaryVals)
 * @method TagTableSelect select(array $whereEquals = [])
 * @method TagRow newRow(array $cols = [])
 * @method TagRow newSelectedRow(array $cols)
 */
abstract class TagTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'tags';

    public const COLUMNS = [
        'tag_id' => [
            'name' => 'tag_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'tag_id',    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = 'tag_id';

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = TagRow;
}
