<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Post\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Post\PostRecord;
use Atlas\Mapper\DataSource\Post\PostRecordSet;
use Atlas\Mapper\DataSource\Post\PostSelect;
use Atlas\Mapper\DataSource\Post\PostTable;

/**
 * @method PostTable getTable()
 * @method ?PostRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?PostRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method PostRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method PostRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method PostRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method PostRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method PostSelect select(array $whereEquals = [])
 * @method PostRecord newRecord(array $fields = [])
 * @method PostRecord[] newRecords(array $fieldSets)
 * @method PostRecordSet newRecordSet(array $records = [])
 * @method PostRecord turnRowIntoRecord(PostRow $row, array $loadRelated = [])
 * @method PostRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Post_ extends Mapper
{
}
