<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Post\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\DataSource\Post\PostRow;
use Atlas\Mapper\DataSource\Post\PostTableSelect;

/**
 * @method ?PostRow fetchRow(mixed $primaryVal)
 * @method PostRow[] fetchRows(array $primaryVals)
 * @method PostTableSelect select(array $whereEquals = [])
 * @method PostRow newRow(array $cols = [])
 * @method PostRow newSelectedRow(array $cols)
 */
abstract class PostTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'posts';

    public const COLUMNS = [
        'post_id' => [
            'name' => 'post_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'subj' => [
            'name' => 'subj',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'body' => [
            'name' => 'body',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'post_id',    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = 'post_id';

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = PostRow;
}
