<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Reply\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $reply_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $author_id INTEGER NOT NULL
 * @property mixed $body TEXT
 * @property ?\Atlas\Mapper\DataSource\Author\AuthorRecord $author
 * @method \Atlas\Mapper\DataSource\Reply\ReplyRow getRow()
 */
abstract class ReplyRecord_ extends Record
{
}
