<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Reply\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\DataSource\Reply\ReplyRow;

/**
 * @method ?ReplyRow fetchRow()
 * @method ReplyRow[] fetchRows()
 */
abstract class ReplyTableSelect_ extends TableSelect
{
}
