<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Video\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Mapper\DataSource\Video\VideoRecord;
use Atlas\Mapper\DataSource\Video\VideoRecordSet;

/**
 * @method __construct(VideoRecord[], callable $newRecordFactory)
 * @method VideoRecord offsetGet($offset)
 * @method VideoRecord appendNew(array $fields = [])
 * @method ?VideoRecord getOneBy(array $whereEquals)
 * @method VideoRecordSet getAllBy(array $whereEquals)
 * @method ?VideoRecord detachOneBy(array $whereEquals)
 * @method VideoRecordSet detachAllBy(array $whereEquals)
 * @method VideoRecordSet detachAll()
 * @method VideoRecordSet detachDeleted()
 */
abstract class VideoRecordSet_ extends RecordSet
{
}
