<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Video\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\DataSource\Video\VideoRow;

/**
 * @method ?VideoRow fetchRow()
 * @method VideoRow[] fetchRows()
 */
abstract class VideoTableSelect_ extends TableSelect
{
}
