<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Thread\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Mapper\DataSource\Thread\ThreadRecord;
use Atlas\Mapper\DataSource\Thread\ThreadRecordSet;

/**
 * @method __construct(ThreadRecord[], callable $newRecordFactory)
 * @method ThreadRecord offsetGet($offset)
 * @method ThreadRecord appendNew(array $fields = [])
 * @method ?ThreadRecord getOneBy(array $whereEquals)
 * @method ThreadRecordSet getAllBy(array $whereEquals)
 * @method ?ThreadRecord detachOneBy(array $whereEquals)
 * @method ThreadRecordSet detachAllBy(array $whereEquals)
 * @method ThreadRecordSet detachAll()
 * @method ThreadRecordSet detachDeleted()
 */
abstract class ThreadRecordSet_ extends RecordSet
{
}
