<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Thread\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Thread\ThreadRecord;
use Atlas\Mapper\DataSource\Thread\ThreadRecordSet;

/**
 * @method ?ThreadRecord fetchRecord()
 * @method ThreadRecord[] fetchRecords()
 * @method ThreadRecordSet fetchRecordSet()
 * @method ?ThreadRow fetchRow()
 * @method ThreadRow[] fetchRows()
 */
abstract class ThreadSelect_ extends MapperSelect
{
}
