<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Thread\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\DataSource\Thread\ThreadRow;
use Atlas\Mapper\DataSource\Thread\ThreadTableSelect;

/**
 * @method ?ThreadRow fetchRow(mixed $primaryVal)
 * @method ThreadRow[] fetchRows(array $primaryVals)
 * @method ThreadTableSelect select(array $whereEquals = [])
 * @method ThreadRow newRow(array $cols = [])
 * @method ThreadRow newSelectedRow(array $cols)
 */
abstract class ThreadTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'threads';

    public const COLUMNS = [
        'thread_id' => [
            'name' => 'thread_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'author_id' => [
            'name' => 'author_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'subject' => [
            'name' => 'subject',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'body' => [
            'name' => 'body',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'thread_id',    ];

    public const COMPOSITE_KEY = false;

    public const AUTOINC_COLUMN = 'thread_id';

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = ThreadRow;
}
