<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace {NAMESPACE}\{TYPE};

use Atlas\Table\Row;

/**
{PROPERTIES}
 */
class {TYPE}Row extends Row
{
    protected $cols = {COLUMN_DEFAULTS};
}
