<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace {NAMESPACE}\{TYPE};

use Atlas\Table\Table;

class {TYPE}Table extends Table
{
    const NAME = {NAME};

    const COLUMNS = {COLUMNS};

    const COLUMN_NAMES = {COLUMN_NAMES};

    const COLUMN_DEFAULTS = {COLUMN_DEFAULTS};

    const PRIMARY_KEY = {PRIMARY_KEY};

    const AUTOINC_COLUMN = {AUTOINC_COLUMN};

    const AUTOINC_SEQUENCE = {AUTOINC_SEQUENCE};
}
