<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tagging\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\DataSource\Tagging\TaggingRow;

/**
 * @method ?TaggingRow fetchRow()
 * @method TaggingRow[] fetchRows()
 */
abstract class TaggingTableSelect_ extends TableSelect
{
}
