<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tagging\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Tagging\TaggingRecord;
use Atlas\Mapper\DataSource\Tagging\TaggingRecordSet;

/**
 * @method ?TaggingRecord fetchRecord()
 * @method TaggingRecord[] fetchRecords()
 * @method TaggingRecordSet fetchRecordSet()
 * @method ?TaggingRow fetchRow()
 * @method TaggingRow[] fetchRows()
 */
abstract class TaggingSelect_ extends MapperSelect
{
}
