<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tagging\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $tagging_id INTEGER
 * @property mixed $thread_id INTEGER
 * @property mixed $tag_id INTEGER
 * @property ?\Atlas\Mapper\DataSource\Thread\ThreadRecord $thread
 * @property ?\Atlas\Mapper\DataSource\Tag\TagRecord $tag
 * @method \Atlas\Mapper\DataSource\Tagging\TaggingRow getRow()
 */
abstract class TaggingRecord_ extends Record
{
}
