<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tagging\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\DataSource\Tagging\TaggingRecord;
use Atlas\Mapper\DataSource\Tagging\TaggingRecordSet;
use Atlas\Mapper\DataSource\Tagging\TaggingSelect;
use Atlas\Mapper\DataSource\Tagging\TaggingTable;

/**
 * @method TaggingTable getTable()
 * @method ?TaggingRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?TaggingRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method TaggingRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method TaggingRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method TaggingRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method TaggingRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method TaggingSelect select(array $whereEquals = [])
 * @method TaggingRecord newRecord(array $fields = [])
 * @method TaggingRecord[] newRecords(array $fieldSets)
 * @method TaggingRecordSet newRecordSet(array $records = [])
 * @method TaggingRecord turnRowIntoRecord(TaggingRow $row, array $loadRelated = [])
 * @method TaggingRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Tagging_ extends Mapper
{
}
