<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidibar\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\DataSource\Bidibar\BidibarRecord;
use Atlas\Mapper\DataSource\Bidibar\BidibarRecordSet;

/**
 * @method ?BidibarRecord fetchRecord()
 * @method BidibarRecord[] fetchRecords()
 * @method BidibarRecordSet fetchRecordSet()
 * @method ?BidibarRow fetchRow()
 * @method BidibarRow[] fetchRows()
 */
abstract class BidibarSelect_ extends MapperSelect
{
}
