<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidibar\_generated;

use Atlas\Mapper\Related;

abstract class BidibarRelated_ extends Related
{
}
