<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Page\_generated;

use Atlas\Table\Row;

/**
 * @property mixed $page_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $body TEXT
 */
abstract class PageRow_ extends Row
{
    protected mixed $page_id = null;
    protected mixed $title = null;
    protected mixed $body = null;
}
