<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Page\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $page_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $body TEXT
 * @property \Atlas\Mapper\DataSource\Comment\CommentRecordSet $comments
 * @method \Atlas\Mapper\DataSource\Page\PageRow getRow()
 */
abstract class PageRecord_ extends Record
{
}
